    -- TILP - CIGARETTE CARD COLLECTING --
    -- add text to rsg-core>shared> items.lua

    card_storage_box        = {name = 'card_storage_box',       label = 'Storage Cards',            weight = 50,  type = 'item',    image = 'card_storage_box.png',         unique = true,   useable = true,  shouldClose = true,  combinable = nil,    description = 'Used to store cigarette collector cards' },
    ---------------------------------------
    -- CARDS DROP --
    ---------------------------------------
    card_package_cards       = {name = 'card_package_cards',    label = 'Package cards',           weight = 0,  type = 'item',     image = 'collector_envelope.png',       unique = false,  useable = true,  shouldClose = true,  combinable = nil,    description = 'Discover new cards to sell or trade'},
    ---------------------------------------
    -- Stars of the stage
    ---------------------------------------
    card_cigcard_act        = {name = 'card_cigcard_act',       label = 'Stars of the stage Set',   weight = 0, type = 'item',      image = 'card_package_box_act.png',     unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card set for sale or exchange'},
    card_cigcard_act_c1     = {name = 'card_cigcard_act_c1',    label = 'Stars of the stage Nº1',   weight = 0, type = 'item',      image = 's_inv_cigcard_act_01x.png',    unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_act_c2     = {name = 'card_cigcard_act_c2',    label = 'Stars of the stage Nº2',   weight = 0, type = 'item',      image = 's_inv_cigcard_act_02x.png',    unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_act_c3     = {name = 'card_cigcard_act_c3',    label = 'Stars of the stage Nº3',   weight = 0, type = 'item',      image = 's_inv_cigcard_act_03x.png',    unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_act_c4     = {name = 'card_cigcard_act_c4',    label = 'Stars of the stage Nº4',   weight = 0, type = 'item',      image = 's_inv_cigcard_act_04x.png',    unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_act_c5     = {name = 'card_cigcard_act_c5',    label = 'Stars of the stage Nº5',   weight = 0, type = 'item',      image = 's_inv_cigcard_act_05x.png',    unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_act_c6     = {name = 'card_cigcard_act_c6',    label = 'Stars of the stage Nº6',   weight = 0, type = 'item',      image = 's_inv_cigcard_act_06x.png',    unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_act_c7     = {name = 'card_cigcard_act_c7',    label = 'Stars of the stage Nº7',   weight = 0, type = 'item',      image = 's_inv_cigcard_act_07x.png',    unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_act_c8     = {name = 'card_cigcard_act_c8',    label = 'Stars of the stage Nº8',   weight = 0, type = 'item',      image = 's_inv_cigcard_act_08x.png',    unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_act_c9     = {name = 'card_cigcard_act_c9',    label = 'Stars of the stage Nº9',   weight = 0, type = 'item',      image = 's_inv_cigcard_act_09x.png',    unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_act_c10    = {name = 'card_cigcard_act_c10',   label = 'Stars of the stage Nº10',  weight = 0, type = 'item',      image = 's_inv_cigcard_act_10x.png',    unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_act_c11    = {name = 'card_cigcard_act_c11',   label = 'Stars of the stage Nº11',  weight = 0, type = 'item',      image = 's_inv_cigcard_act_11x.png',    unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_act_c12    = {name = 'card_cigcard_act_c12',   label = 'Stars of the stage Nº12',  weight = 0, type = 'item',      image = 's_inv_cigcard_act_12x.png',    unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    ---------------------------------------
    -- Prominent Americans
    ---------------------------------------
    card_cigcard_amer       = {name = 'card_cigcard_amer',      label = 'Prominent Americans Set',  weight = 0, type = 'item',  image = 'card_package_box_amer.png',    unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card set for sale or exchange'},
    card_cigcard_amer_c1    = {name = 'card_cigcard_amer_c1',   label = 'Prominent Americans Nº1',  weight = 0, type = 'item',  image = 's_inv_cigcard_amer_01x.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_amer_c2    = {name = 'card_cigcard_amer_c2',   label = 'Prominent Americans Nº2',  weight = 0, type = 'item',  image = 's_inv_cigcard_amer_02x.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_amer_c3    = {name = 'card_cigcard_amer_c3',   label = 'Prominent Americans Nº3',  weight = 0, type = 'item',  image = 's_inv_cigcard_amer_03x.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_amer_c4    = {name = 'card_cigcard_amer_c4',   label = 'Prominent Americans Nº4',  weight = 0, type = 'item',  image = 's_inv_cigcard_amer_04x.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_amer_c5    = {name = 'card_cigcard_amer_c5',   label = 'Prominent Americans Nº5',  weight = 0, type = 'item',  image = 's_inv_cigcard_amer_05x.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_amer_c6    = {name = 'card_cigcard_amer_c6',   label = 'Prominent Americans Nº6',  weight = 0, type = 'item',  image = 's_inv_cigcard_amer_06x.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_amer_c7    = {name = 'card_cigcard_amer_c7',   label = 'Prominent Americans Nº7',  weight = 0, type = 'item',  image = 's_inv_cigcard_amer_07x.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_amer_c8    = {name = 'card_cigcard_amer_c8',   label = 'Prominent Americans Nº8',  weight = 0, type = 'item',  image = 's_inv_cigcard_amer_08x.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_amer_c9    = {name = 'card_cigcard_amer_c9',   label = 'Prominent Americans Nº9',  weight = 0, type = 'item',  image = 's_inv_cigcard_amer_09x.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_amer_c10   = {name = 'card_cigcard_amer_c10',  label = 'Prominent Americans Nº10', weight = 0, type = 'item',  image = 's_inv_cigcard_amer_10x.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_amer_c11   = {name = 'card_cigcard_amer_c11',  label = 'Prominent Americans Nº11', weight = 0, type = 'item',  image = 's_inv_cigcard_amer_11x.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_amer_c12   = {name = 'card_cigcard_amer_c12',  label = 'Prominent Americans Nº12', weight = 0, type = 'item',  image = 's_inv_cigcard_amer_12x.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    ---------------------------------------
    -- Fauna of North America
    ---------------------------------------
    card_cigcard_aml        = {name = 'card_cigcard_aml',       label = 'Fauna of North America Set',   weight = 0, type = 'item',  image = 'card_package_box_art.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card set for sale or exchange'},
    card_cigcard_aml_c1     = {name = 'card_cigcard_aml_c1',    label = 'Fauna of North America Nº1',   weight = 0, type = 'item',  image = 's_inv_cigcard_aml_01x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_aml_c2     = {name = 'card_cigcard_aml_c2',    label = 'Fauna of North America Nº2',   weight = 0, type = 'item',  image = 's_inv_cigcard_aml_02x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_aml_c3     = {name = 'card_cigcard_aml_c3',    label = 'Fauna of North America Nº3',   weight = 0, type = 'item',  image = 's_inv_cigcard_aml_03x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_aml_c4     = {name = 'card_cigcard_aml_c4',    label = 'Fauna of North America Nº4',   weight = 0, type = 'item',  image = 's_inv_cigcard_aml_04x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_aml_c5     = {name = 'card_cigcard_aml_c5',    label = 'Fauna of North America Nº5',   weight = 0, type = 'item',  image = 's_inv_cigcard_aml_05x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_aml_c6     = {name = 'card_cigcard_aml_c6',    label = 'Fauna of North America Nº6',   weight = 0, type = 'item',  image = 's_inv_cigcard_aml_06x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_aml_c7     = {name = 'card_cigcard_aml_c7',    label = 'Fauna of North America Nº7',   weight = 0, type = 'item',  image = 's_inv_cigcard_aml_07x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_aml_c8     = {name = 'card_cigcard_aml_c8',    label = 'Fauna of North America Nº8',   weight = 0, type = 'item',  image = 's_inv_cigcard_aml_08x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_aml_c9     = {name = 'card_cigcard_aml_c9',    label = 'Fauna of North America Nº9',   weight = 0, type = 'item',  image = 's_inv_cigcard_aml_09x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_aml_c10    = {name = 'card_cigcard_aml_c10',   label = 'Fauna of North America Nº10',  weight = 0, type = 'item',  image = 's_inv_cigcard_aml_10x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_aml_c11    = {name = 'card_cigcard_aml_c11',   label = 'Fauna of North America Nº11',  weight = 0, type = 'item',  image = 's_inv_cigcard_aml_11x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_aml_c12    = {name = 'card_cigcard_aml_c12',   label = 'Fauna of North America Nº12',  weight = 0, type = 'item',  image = 's_inv_cigcard_aml_12x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    ---------------------------------------
    -- Artists, Painters, Writers and Poets
    ---------------------------------------
    card_cigcard_art      = {name = 'card_cigcard_art',        label = 'Artists Set',   weight = 0, type = 'item',  image = 'card_package_box_art.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card set for sale or exchange'},
    card_cigcard_art_c1   = {name = 'card_cigcard_art_c1',     label = 'Artists Nº1',   weight = 0, type = 'item',  image = 's_inv_cigcard_art_01x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_art_c2   = {name = 'card_cigcard_art_c2',     label = 'Artists Nº2',   weight = 0, type = 'item',  image = 's_inv_cigcard_art_02x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_art_c3   = {name = 'card_cigcard_art_c3',     label = 'Artists Nº3',   weight = 0, type = 'item',  image = 's_inv_cigcard_art_03x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_art_c4   = {name = 'card_cigcard_art_c4',     label = 'Artists Nº4',   weight = 0, type = 'item',  image = 's_inv_cigcard_art_04x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_art_c5   = {name = 'card_cigcard_art_c5',     label = 'Artists Nº5',   weight = 0, type = 'item',  image = 's_inv_cigcard_art_05x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_art_c6   = {name = 'card_cigcard_art_c6',     label = 'Artists Nº6',   weight = 0, type = 'item',  image = 's_inv_cigcard_art_06x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_art_c7   = {name = 'card_cigcard_art_c7',     label = 'Artists Nº7',   weight = 0, type = 'item',  image = 's_inv_cigcard_art_07x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_art_c8   = {name = 'card_cigcard_art_c8',     label = 'Artists Nº8',   weight = 0, type = 'item',  image = 's_inv_cigcard_art_08x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_art_c9   = {name = 'card_cigcard_art_c9',     label = 'Artists Nº9',   weight = 0, type = 'item',  image = 's_inv_cigcard_art_09x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_art_c10  = {name = 'card_cigcard_art_c10',    label = 'Artists Nº10',  weight = 0, type = 'item',  image = 's_inv_cigcard_art_10x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_art_c11  = {name = 'card_cigcard_art_c11',    label = 'Artists Nº11',  weight = 0, type = 'item',  image = 's_inv_cigcard_art_11x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_art_c12  = {name = 'card_cigcard_art_c12',    label = 'Artists Nº12',  weight = 0, type = 'item',  image = 's_inv_cigcard_art_12x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    ---------------------------------------
    -- Fairest Flowers and Gems of Beauty
    ---------------------------------------
    card_cigcard_grl      = {name = 'card_cigcard_grl',         label = 'Fairest Flowers and Gems of Beauty Set',      weight = 0, type = 'item',  image = 'card_package_box_grl.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card set for sale or exchange'},
    card_cigcard_grl_c1   = {name = 'card_cigcard_grl_c1',      label = 'Fairest Flowers and Gems of Beauty Nº1',      weight = 0, type = 'item',  image = 's_inv_cigcard_grl_01x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_grl_c2   = {name = 'card_cigcard_grl_c2',      label = 'Fairest Flowers and Gems of Beauty Nº2',      weight = 0, type = 'item',  image = 's_inv_cigcard_grl_02x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_grl_c3   = {name = 'card_cigcard_grl_c3',      label = 'Fairest Flowers and Gems of Beauty Nº3',      weight = 0, type = 'item',  image = 's_inv_cigcard_grl_03x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_grl_c4   = {name = 'card_cigcard_grl_c4',      label = 'Fairest Flowers and Gems of Beauty Nº4',      weight = 0, type = 'item',  image = 's_inv_cigcard_grl_04x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_grl_c5   = {name = 'card_cigcard_grl_c5',      label = 'Fairest Flowers and Gems of Beauty Nº5',      weight = 0, type = 'item',  image = 's_inv_cigcard_grl_05x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_grl_c6   = {name = 'card_cigcard_grl_c6',      label = 'Fairest Flowers and Gems of Beauty Nº6',      weight = 0, type = 'item',  image = 's_inv_cigcard_grl_06x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_grl_c7   = {name = 'card_cigcard_grl_c7',      label = 'Fairest Flowers and Gems of Beauty Nº7',      weight = 0, type = 'item',  image = 's_inv_cigcard_grl_07x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_grl_c8   = {name = 'card_cigcard_grl_c8',      label = 'Fairest Flowers and Gems of Beauty Nº8',      weight = 0, type = 'item',  image = 's_inv_cigcard_grl_08x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_grl_c9   = {name = 'card_cigcard_grl_c9',      label = 'Fairest Flowers and Gems of Beauty Nº9',      weight = 0, type = 'item',  image = 's_inv_cigcard_grl_09x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_grl_c10  = {name = 'card_cigcard_grl_c10',     label = 'Fairest Flowers and Gems of Beauty Nº10',     weight = 0, type = 'item',  image = 's_inv_cigcard_grl_10x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_grl_c11  = {name = 'card_cigcard_grl_c11',     label = 'Fairest Flowers and Gems of Beauty Nº11',     weight = 0, type = 'item',  image = 's_inv_cigcard_grl_11x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_grl_c12  = {name = 'card_cigcard_grl_c12',     label = 'Fairest Flowers and Gems of Beauty Nº12',     weight = 0, type = 'item',  image = 's_inv_cigcard_grl_12x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    ---------------------------------------
    -- Famous Gunslingers and Outlaws
    ---------------------------------------
    card_cigcard_gun      = {name = 'card_cigcard_gun',         label = 'Famous Gunslingers and Outlaws Deck',      weight = 0, type = 'item',  image = 'card_package_box_gun.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card set for sale or exchange'},
    card_cigcard_gun_c1   = {name = 'card_cigcard_gun_c1',      label = 'Famous Gunslingers and Outlaws Nº1',       weight = 0, type = 'item',  image = 's_inv_cigcard_gun_01x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_gun_c2   = {name = 'card_cigcard_gun_c2',      label = 'Famous Gunslingers and Outlaws Nº2',       weight = 0, type = 'item',  image = 's_inv_cigcard_gun_02x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_gun_c3   = {name = 'card_cigcard_gun_c3',      label = 'Famous Gunslingers and Outlaws Nº3',       weight = 0, type = 'item',  image = 's_inv_cigcard_gun_03x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_gun_c4   = {name = 'card_cigcard_gun_c4',      label = 'Famous Gunslingers and Outlaws Nº4',       weight = 0, type = 'item',  image = 's_inv_cigcard_gun_04x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_gun_c5   = {name = 'card_cigcard_gun_c5',      label = 'Famous Gunslingers and Outlaws Nº5',       weight = 0, type = 'item',  image = 's_inv_cigcard_gun_05x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_gun_c6   = {name = 'card_cigcard_gun_c6',      label = 'Famous Gunslingers and Outlaws Nº6',       weight = 0, type = 'item',  image = 's_inv_cigcard_gun_06x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_gun_c7   = {name = 'card_cigcard_gun_c7',      label = 'Famous Gunslingers and Outlaws Nº7',       weight = 0, type = 'item',  image = 's_inv_cigcard_gun_07x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_gun_c8   = {name = 'card_cigcard_gun_c8',      label = 'Famous Gunslingers and Outlaws Nº8',       weight = 0, type = 'item',  image = 's_inv_cigcard_gun_08x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_gun_c9   = {name = 'card_cigcard_gun_c9',      label = 'Famous Gunslingers and Outlaws Nº9',       weight = 0, type = 'item',  image = 's_inv_cigcard_gun_09x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_gun_c10  = {name = 'card_cigcard_gun_c10',     label = 'Famous Gunslingers and Outlaws Nº10',      weight = 0, type = 'item',  image = 's_inv_cigcard_gun_10x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_gun_c11  = {name = 'card_cigcard_gun_c11',     label = 'Famous Gunslingers and Outlaws Nº11',      weight = 0, type = 'item',  image = 's_inv_cigcard_gun_11x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_gun_c12  = {name = 'card_cigcard_gun_c12',     label = 'Famous Gunslingers and Outlaws Nº12',      weight = 0, type = 'item',  image = 's_inv_cigcard_gun_12x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    ---------------------------------------
    -- Breeds of Horses
    ---------------------------------------
    card_cigcard_hrs      = {name = 'card_cigcard_hrs',         label = 'Breeds of Horses Deck',     weight = 0, type = 'item',  image = 'card_package_box_hrs.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card set for sale or exchange'},
    card_cigcard_hrs_c1   = {name = 'card_cigcard_hrs_c1',      label = 'Breeds of Horses Nº1',      weight = 0, type = 'item',  image = 's_inv_cigcard_hrs_01x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_hrs_c2   = {name = 'card_cigcard_hrs_c2',      label = 'Breeds of Horses Nº2',      weight = 0, type = 'item',  image = 's_inv_cigcard_hrs_02x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_hrs_c3   = {name = 'card_cigcard_hrs_c3',      label = 'Breeds of Horses Nº3',      weight = 0, type = 'item',  image = 's_inv_cigcard_hrs_03x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_hrs_c4   = {name = 'card_cigcard_hrs_c4',      label = 'Breeds of Horses Nº4',      weight = 0, type = 'item',  image = 's_inv_cigcard_hrs_04x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_hrs_c5   = {name = 'card_cigcard_hrs_c5',      label = 'Breeds of Horses Nº5',      weight = 0, type = 'item',  image = 's_inv_cigcard_hrs_05x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_hrs_c6   = {name = 'card_cigcard_hrs_c6',      label = 'Breeds of Horses Nº6',      weight = 0, type = 'item',  image = 's_inv_cigcard_hrs_06x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_hrs_c7   = {name = 'card_cigcard_hrs_c7',      label = 'Breeds of Horses Nº7',      weight = 0, type = 'item',  image = 's_inv_cigcard_hrs_07x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_hrs_c8   = {name = 'card_cigcard_hrs_c8',      label = 'Breeds of Horses Nº8',      weight = 0, type = 'item',  image = 's_inv_cigcard_hrs_08x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_hrs_c9   = {name = 'card_cigcard_hrs_c9',      label = 'Breeds of Horses Nº9',      weight = 0, type = 'item',  image = 's_inv_cigcard_hrs_09x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_hrs_c10  = {name = 'card_cigcard_hrs_c10',     label = 'Breeds of Horses Nº10',     weight = 0, type = 'item',  image = 's_inv_cigcard_hrs_10x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_hrs_c11  = {name = 'card_cigcard_hrs_c11',     label = 'Breeds of Horses Nº11',     weight = 0, type = 'item',  image = 's_inv_cigcard_hrs_11x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_hrs_c12  = {name = 'card_cigcard_hrs_c12',     label = 'Breeds of Horses Nº12',     weight = 0, type = 'item',  image = 's_inv_cigcard_hrs_12x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    ---------------------------------------
    -- Amazing Inventions
    ---------------------------------------
    card_cigcard_inv      = {name = 'card_cigcard_inv',         label = 'Inventions Deck',     weight = 0, type = 'item',  image = 'card_package_box_inv.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card set for sale or exchange'},
    card_cigcard_inv_c1   = {name = 'card_cigcard_inv_c1',      label = 'Inventions Nº1',      weight = 0, type = 'item',  image = 's_inv_cigcard_inv_01x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_inv_c2   = {name = 'card_cigcard_inv_c2',      label = 'Inventions Nº2',      weight = 0, type = 'item',  image = 's_inv_cigcard_inv_02x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_inv_c3   = {name = 'card_cigcard_inv_c3',      label = 'Inventions Nº3',      weight = 0, type = 'item',  image = 's_inv_cigcard_inv_03x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_inv_c4   = {name = 'card_cigcard_inv_c4',      label = 'Inventions Nº4',      weight = 0, type = 'item',  image = 's_inv_cigcard_inv_04x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_inv_c5   = {name = 'card_cigcard_inv_c5',      label = 'Inventions Nº5',      weight = 0, type = 'item',  image = 's_inv_cigcard_inv_05x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_inv_c6   = {name = 'card_cigcard_inv_c6',      label = 'Inventions Nº6',      weight = 0, type = 'item',  image = 's_inv_cigcard_inv_06x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_inv_c7   = {name = 'card_cigcard_inv_c7',      label = 'Inventions Nº7',      weight = 0, type = 'item',  image = 's_inv_cigcard_inv_07x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_inv_c8   = {name = 'card_cigcard_inv_c8',      label = 'Inventions Nº8',      weight = 0, type = 'item',  image = 's_inv_cigcard_inv_08x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_inv_c9   = {name = 'card_cigcard_inv_c9',      label = 'Inventions Nº9',      weight = 0, type = 'item',  image = 's_inv_cigcard_inv_09x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_inv_c10  = {name = 'card_cigcard_inv_c10',     label = 'Inventions Nº10',     weight = 0, type = 'item',  image = 's_inv_cigcard_inv_10x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_inv_c11  = {name = 'card_cigcard_inv_c11',     label = 'Inventions Nº11',     weight = 0, type = 'item',  image = 's_inv_cigcard_inv_11x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_inv_c12  = {name = 'card_cigcard_inv_c12',     label = 'Inventions Nº12',     weight = 0, type = 'item',  image = 's_inv_cigcard_inv_12x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    ---------------------------------------
    -- Vistas, Scenery and Cities of America
    ---------------------------------------
    card_cigcard_lnd      = {name = 'card_cigcard_lnd',         label = 'America Deck',     weight = 0, type = 'item',  image = 'card_package_box_lnd.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,    description = 'Collectible card set for sale or exchange'},
    card_cigcard_lnd_c1   = {name = 'card_cigcard_lnd_c1',      label = 'America Nº1',      weight = 0, type = 'item',  image = 's_inv_cigcard_lnd_01x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_lnd_c2   = {name = 'card_cigcard_lnd_c2',      label = 'America Nº2',      weight = 0, type = 'item',  image = 's_inv_cigcard_lnd_02x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_lnd_c3   = {name = 'card_cigcard_lnd_c3',      label = 'America Nº3',      weight = 0, type = 'item',  image = 's_inv_cigcard_lnd_03x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_lnd_c4   = {name = 'card_cigcard_lnd_c4',      label = 'America Nº4',      weight = 0, type = 'item',  image = 's_inv_cigcard_lnd_04x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_lnd_c5   = {name = 'card_cigcard_lnd_c5',      label = 'America Nº5',      weight = 0, type = 'item',  image = 's_inv_cigcard_lnd_05x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_lnd_c6   = {name = 'card_cigcard_lnd_c6',      label = 'America Nº6',      weight = 0, type = 'item',  image = 's_inv_cigcard_lnd_06x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_lnd_c7   = {name = 'card_cigcard_lnd_c7',      label = 'America Nº7',      weight = 0, type = 'item',  image = 's_inv_cigcard_lnd_07x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_lnd_c8   = {name = 'card_cigcard_lnd_c8',      label = 'America Nº8',      weight = 0, type = 'item',  image = 's_inv_cigcard_lnd_08x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_lnd_c9   = {name = 'card_cigcard_lnd_c9',      label = 'America Nº9',      weight = 0, type = 'item',  image = 's_inv_cigcard_lnd_09x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_lnd_c10  = {name = 'card_cigcard_lnd_c10',     label = 'America Nº10',     weight = 0, type = 'item',  image = 's_inv_cigcard_lnd_10x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_lnd_c11  = {name = 'card_cigcard_lnd_c11',     label = 'America Nº11',     weight = 0, type = 'item',  image = 's_inv_cigcard_lnd_11x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_lnd_c12  = {name = 'card_cigcard_lnd_c12',     label = 'America Nº12',     weight = 0, type = 'item',  image = 's_inv_cigcard_lnd_12x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    ---------------------------------------
    -- Wild Flora of North America
    ---------------------------------------
    card_cigcard_plt      = {name = 'card_cigcard_plt',         label = 'Wild Flora of North America Deck',     weight = 0, type = 'item',  image = 'card_package_box_plt.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card set for sale or exchange'},
    card_cigcard_plt_c1   = {name = 'card_cigcard_plt_c1',      label = 'Wild Flora of North America Nº1',      weight = 0, type = 'item',  image = 's_inv_cigcard_plt_01x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_plt_c2   = {name = 'card_cigcard_plt_c2',      label = 'Wild Flora of North America Nº2',      weight = 0, type = 'item',  image = 's_inv_cigcard_plt_02x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_plt_c3   = {name = 'card_cigcard_plt_c3',      label = 'Wild Flora of North America Nº3',      weight = 0, type = 'item',  image = 's_inv_cigcard_plt_03x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_plt_c4   = {name = 'card_cigcard_plt_c4',      label = 'Wild Flora of North America Nº4',      weight = 0, type = 'item',  image = 's_inv_cigcard_plt_04x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_plt_c5   = {name = 'card_cigcard_plt_c5',      label = 'Wild Flora of North America Nº5',      weight = 0, type = 'item',  image = 's_inv_cigcard_plt_05x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_plt_c6   = {name = 'card_cigcard_plt_c6',      label = 'Wild Flora of North America Nº6',      weight = 0, type = 'item',  image = 's_inv_cigcard_plt_06x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_plt_c7   = {name = 'card_cigcard_plt_c7',      label = 'Wild Flora of North America Nº7',      weight = 0, type = 'item',  image = 's_inv_cigcard_plt_07x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_plt_c8   = {name = 'card_cigcard_plt_c8',      label = 'Wild Flora of North America Nº8',      weight = 0, type = 'item',  image = 's_inv_cigcard_plt_08x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_plt_c9   = {name = 'card_cigcard_plt_c9',      label = 'Wild Flora of North America Nº9',      weight = 0, type = 'item',  image = 's_inv_cigcard_plt_09x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_plt_c10  = {name = 'card_cigcard_plt_c10',     label = 'Wild Flora of North America Nº10',     weight = 0, type = 'item',  image = 's_inv_cigcard_plt_10x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_plt_c11  = {name = 'card_cigcard_plt_c11',     label = 'Wild Flora of North America Nº11',     weight = 0, type = 'item',  image = 's_inv_cigcard_plt_11x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_plt_c12  = {name = 'card_cigcard_plt_c12',     label = 'Wild Flora of North America Nº12',     weight = 0, type = 'item',  image = 's_inv_cigcard_plt_12x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},   
    ---------------------------------------
    -- The World's Champions
    ---------------------------------------
    card_cigcard_spt      = {name = 'card_cigcard_spt',         label = 'The Worlds Champions Deck',     weight = 0, type = 'item',  image = 'card_package_box_spt.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card set for sale or exchange'},
    card_cigcard_spt_c1   = {name = 'card_cigcard_spt_c1',      label = 'The Worlds Champions Nº1',      weight = 0, type = 'item',  image = 's_inv_cigcard_spt_01x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_spt_c2   = {name = 'card_cigcard_spt_c2',      label = 'The Worlds Champions Nº2',      weight = 0, type = 'item',  image = 's_inv_cigcard_spt_02x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_spt_c3   = {name = 'card_cigcard_spt_c3',      label = 'The Worlds Champions Nº3',      weight = 0, type = 'item',  image = 's_inv_cigcard_spt_03x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_spt_c4   = {name = 'card_cigcard_spt_c4',      label = 'The Worlds Champions Nº4',      weight = 0, type = 'item',  image = 's_inv_cigcard_spt_04x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_spt_c5   = {name = 'card_cigcard_spt_c5',      label = 'The Worlds Champions Nº5',      weight = 0, type = 'item',  image = 's_inv_cigcard_spt_05x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_spt_c6   = {name = 'card_cigcard_spt_c6',      label = 'The Worlds Champions Nº6',      weight = 0, type = 'item',  image = 's_inv_cigcard_spt_06x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_spt_c7   = {name = 'card_cigcard_spt_c7',      label = 'The Worlds Champions Nº7',      weight = 0, type = 'item',  image = 's_inv_cigcard_spt_07x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_spt_c8   = {name = 'card_cigcard_spt_c8',      label = 'The Worlds Champions Nº8',      weight = 0, type = 'item',  image = 's_inv_cigcard_spt_08x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_spt_c9   = {name = 'card_cigcard_spt_c9',      label = 'The Worlds Champions Nº9',      weight = 0, type = 'item',  image = 's_inv_cigcard_spt_09x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_spt_c10  = {name = 'card_cigcard_spt_c10',     label = 'The Worlds Champions Nº10',     weight = 0, type = 'item',  image = 's_inv_cigcard_spt_10x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_spt_c11  = {name = 'card_cigcard_spt_c11',     label = 'The Worlds Champions Nº11',     weight = 0, type = 'item',  image = 's_inv_cigcard_spt_11x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_spt_c12  = {name = 'card_cigcard_spt_c12',     label = 'The Worlds Champions Nº12',     weight = 0, type = 'item',  image = 's_inv_cigcard_spt_12x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    ---------------------------------------
    -- Amazing Inventions
    ---------------------------------------
    card_cigcard_veh      = {name = 'card_cigcard_veh',         label = 'Amazing Inventions Deck',     weight = 0, type = 'item',  image = 'card_package_box_inv.png',   unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card set for sale or exchange'},
    card_cigcard_veh_c1   = {name = 'card_cigcard_veh_c1',      label = 'Amazing Inventions Nº1',      weight = 0, type = 'item',  image = 's_inv_cigcard_veh_01x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_veh_c2   = {name = 'card_cigcard_veh_c2',      label = 'Amazing Inventions Nº2',      weight = 0, type = 'item',  image = 's_inv_cigcard_veh_02x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_veh_c3   = {name = 'card_cigcard_veh_c3',      label = 'Amazing Inventions Nº3',      weight = 0, type = 'item',  image = 's_inv_cigcard_veh_03x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_veh_c4   = {name = 'card_cigcard_veh_c4',      label = 'Amazing Inventions Nº4',      weight = 0, type = 'item',  image = 's_inv_cigcard_veh_04x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_veh_c5   = {name = 'card_cigcard_veh_c5',      label = 'Amazing Inventions Nº5',      weight = 0, type = 'item',  image = 's_inv_cigcard_veh_05x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_veh_c6   = {name = 'card_cigcard_veh_c6',      label = 'Amazing Inventions Nº6',      weight = 0, type = 'item',  image = 's_inv_cigcard_veh_06x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_veh_c7   = {name = 'card_cigcard_veh_c7',      label = 'Amazing Inventions Nº7',      weight = 0, type = 'item',  image = 's_inv_cigcard_veh_07x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_veh_c8   = {name = 'card_cigcard_veh_c8',      label = 'Amazing Inventions Nº8',      weight = 0, type = 'item',  image = 's_inv_cigcard_veh_08x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_veh_c9   = {name = 'card_cigcard_veh_c9',      label = 'Amazing Inventions Nº9',      weight = 0, type = 'item',  image = 's_inv_cigcard_veh_09x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_veh_c10  = {name = 'card_cigcard_veh_c10',     label = 'Amazing Inventions Nº10',     weight = 0, type = 'item',  image = 's_inv_cigcard_veh_10x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_veh_c11  = {name = 'card_cigcard_veh_c11',     label = 'Amazing Inventions Nº11',     weight = 0, type = 'item',  image = 's_inv_cigcard_veh_11x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    card_cigcard_veh_c12  = {name = 'card_cigcard_veh_c12',     label = 'Amazing Inventions Nº12',     weight = 0, type = 'item',  image = 's_inv_cigcard_veh_12x.png',  unique = false,  useable = false,  shouldClose = false, combinable = nil,   description = 'Collectible card for sale or exchange'},
    ---------------------------------------