local Missions = {
	{
		Amount 		= 1,
		reward 		= "card_cigcard_act",
        cards = {
			['card_cigcard_act_c1'] 	= 1,
			['card_cigcard_act_c2'] 	= 1,
			['card_cigcard_act_c3'] 	= 1,
			['card_cigcard_act_c4'] 	= 1,
			['card_cigcard_act_c5'] 	= 1,
			['card_cigcard_act_c6'] 	= 1,
			['card_cigcard_act_c7'] 	= 1,
			['card_cigcard_act_c8'] 	= 1,
			['card_cigcard_act_c9'] 	= 1,
			['card_cigcard_act_c10'] 	= 1,
			['card_cigcard_act_c11'] 	= 1,
			['card_cigcard_act_c12'] 	= 1,
		},},
	{
		Amount 		= 1,
		reward 		= "card_cigcard_amer",
        cards = {
			['card_cigcard_amer_c1'] 	= 1,
			['card_cigcard_amer_c2'] 	= 1,
			['card_cigcard_amer_c3'] 	= 1,
			['card_cigcard_amer_c4'] 	= 1,
			['card_cigcard_amer_c5'] 	= 1,
			['card_cigcard_amer_c6'] 	= 1,
			['card_cigcard_amer_c7'] 	= 1,
			['card_cigcard_amer_c8'] 	= 1,
			['card_cigcard_amer_c9'] 	= 1,
			['card_cigcard_amer_c10'] 	= 1,
			['card_cigcard_amer_c11'] 	= 1,
			['card_cigcard_amer_c12'] 	= 1,
		},},
	{
		Amount 		= 1,
		reward 		= "card_cigcard_aml",
        cards = {
			['card_cigcard_aml_c1'] 	= 1,
			['card_cigcard_aml_c2'] 	= 1,
			['card_cigcard_aml_c3'] 	= 1,
			['card_cigcard_aml_c4'] 	= 1,
			['card_cigcard_aml_c5'] 	= 1,
			['card_cigcard_aml_c6'] 	= 1,
			['card_cigcard_aml_c7'] 	= 1,
			['card_cigcard_aml_c8'] 	= 1,
			['card_cigcard_aml_c9'] 	= 1,
			['card_cigcard_aml_c10'] 	= 1,
			['card_cigcard_aml_c11'] 	= 1,
			['card_cigcard_aml_c12'] 	= 1,
		},},
	{
		Amount 		= 1,
		reward 		= "card_cigcard_art",
        cards = {
			['card_cigcard_art_c1'] 	= 1,
			['card_cigcard_art_c2'] 	= 1,
			['card_cigcard_art_c3'] 	= 1,
			['card_cigcard_art_c4'] 	= 1,
			['card_cigcard_art_c5'] 	= 1,
			['card_cigcard_art_c6'] 	= 1,
			['card_cigcard_art_c7'] 	= 1,
			['card_cigcard_art_c8'] 	= 1,
			['card_cigcard_art_c9'] 	= 1,
			['card_cigcard_art_c10'] 	= 1,
			['card_cigcard_art_c11'] 	= 1,
			['card_cigcard_art_c12'] 	= 1,
		},},
	{
		Amount 		= 1,
		reward 		= "card_cigcard_grl",
        cards = {
			['card_cigcard_grl_c1'] 	= 1,
			['card_cigcard_grl_c2'] 	= 1,
			['card_cigcard_grl_c3'] 	= 1,
			['card_cigcard_grl_c4'] 	= 1,
			['card_cigcard_grl_c5'] 	= 1,
			['card_cigcard_grl_c6'] 	= 1,
			['card_cigcard_grl_c7'] 	= 1,
			['card_cigcard_grl_c8'] 	= 1,
			['card_cigcard_grl_c9'] 	= 1,
			['card_cigcard_grl_c10'] 	= 1,
			['card_cigcard_grl_c11'] 	= 1,
			['card_cigcard_grl_c12'] 	= 1,
		},},
	{
		Amount 		= 1,
		reward 		= "card_cigcard_gun",
		cards = {
			['card_cigcard_gun_c1'] 	= 1,
			['card_cigcard_gun_c2'] 	= 1,
			['card_cigcard_gun_c3'] 	= 1,
			['card_cigcard_gun_c4'] 	= 1,
			['card_cigcard_gun_c5'] 	= 1,
			['card_cigcard_gun_c6'] 	= 1,
			['card_cigcard_gun_c7'] 	= 1,
			['card_cigcard_gun_c8'] 	= 1,
			['card_cigcard_gun_c9'] 	= 1,
			['card_cigcard_gun_c10'] 	= 1,
			['card_cigcard_gun_c11'] 	= 1,
			['card_cigcard_gun_c12'] 	= 1,
		},},
	{
		Amount 		= 1,
		reward 		= "card_cigcard_hrs",
        cards = {
			['card_cigcard_hrs_c1'] 	= 1,
			['card_cigcard_hrs_c2'] 	= 1,
			['card_cigcard_hrs_c3'] 	= 1,
			['card_cigcard_hrs_c4'] 	= 1,
			['card_cigcard_hrs_c5'] 	= 1,
			['card_cigcard_hrs_c6'] 	= 1,
			['card_cigcard_hrs_c7'] 	= 1,
			['card_cigcard_hrs_c8'] 	= 1,
			['card_cigcard_hrs_c9'] 	= 1,
			['card_cigcard_hrs_c10'] 	= 1,
			['card_cigcard_hrs_c11'] 	= 1,
			['card_cigcard_hrs_c12'] 	= 1,
		},},
	{
		Amount 		= 1,
		reward 		= "card_cigcard_inv",
        cards = {
			['card_cigcard_inv_c1'] 	= 1,
			['card_cigcard_inv_c2'] 	= 1,
			['card_cigcard_inv_c3'] 	= 1,
			['card_cigcard_inv_c4'] 	= 1,
			['card_cigcard_inv_c5'] 	= 1,
			['card_cigcard_inv_c6'] 	= 1,
			['card_cigcard_inv_c7'] 	= 1,
			['card_cigcard_inv_c8'] 	= 1,
			['card_cigcard_inv_c9'] 	= 1,
			['card_cigcard_inv_c10'] 	= 1,
			['card_cigcard_inv_c11'] 	= 1,
			['card_cigcard_inv_c12'] 	= 1,
		},},
	{
		Amount 		= 1,
		reward 		= "card_cigcard_lnd",
        cards = {
			['card_cigcard_lnd_c1'] 	= 1,
			['card_cigcard_lnd_c2'] 	= 1,
			['card_cigcard_lnd_c3'] 	= 1,
			['card_cigcard_lnd_c4'] 	= 1,
			['card_cigcard_lnd_c5'] 	= 1,
			['card_cigcard_lnd_c6'] 	= 1,
			['card_cigcard_lnd_c7'] 	= 1,
			['card_cigcard_lnd_c8'] 	= 1,
			['card_cigcard_lnd_c9'] 	= 1,
			['card_cigcard_lnd_c10'] 	= 1,
			['card_cigcard_lnd_c11'] 	= 1,
			['card_cigcard_lnd_c12'] 	= 1,
		}},
	{
		Amount 		= 1,
		reward 		= "card_cigcard_plt",
        cards = {
			['card_cigcard_plt_c1'] 	= 1,
			['card_cigcard_plt_c2'] 	= 1,
			['card_cigcard_plt_c3'] 	= 1,
			['card_cigcard_plt_c4'] 	= 1,
			['card_cigcard_plt_c5'] 	= 1,
			['card_cigcard_plt_c6'] 	= 1,
			['card_cigcard_plt_c7'] 	= 1,
			['card_cigcard_plt_c8'] 	= 1,
			['card_cigcard_plt_c9'] 	= 1,
			['card_cigcard_plt_c10'] 	= 1,
			['card_cigcard_plt_c11'] 	= 1,
			['card_cigcard_plt_c12'] 	= 1,
		}},
	{
		Amount 		= 1,
		reward 		= "card_cigcard_spt",
        cards = {
			['card_cigcard_spt_c1'] 	= 1,
			['card_cigcard_spt_c2'] 	= 1,
			['card_cigcard_spt_c3'] 	= 1,
			['card_cigcard_spt_c4'] 	= 1,
			['card_cigcard_spt_c5'] 	= 1,
			['card_cigcard_spt_c6'] 	= 1,
			['card_cigcard_spt_c7'] 	= 1,
			['card_cigcard_spt_c8'] 	= 1,
			['card_cigcard_spt_c9'] 	= 1,
			['card_cigcard_spt_c10'] 	= 1,
			['card_cigcard_spt_c11'] 	= 1,
			['card_cigcard_spt_c12'] 	= 1,
		}},
	{
		Amount 		= 1,
		reward 		= "card_cigcard_veh",
        cards = {
			['card_cigcard_veh_c1'] 	= 1,
			['card_cigcard_veh_c2'] 	= 1,
			['card_cigcard_veh_c3'] 	= 1,
			['card_cigcard_veh_c4'] 	= 1,
			['card_cigcard_veh_c5'] 	= 1,
			['card_cigcard_veh_c6'] 	= 1,
			['card_cigcard_veh_c7'] 	= 1,
			['card_cigcard_veh_c8'] 	= 1,
			['card_cigcard_veh_c9'] 	= 1,
			['card_cigcard_veh_c10'] 	= 1,
			['card_cigcard_veh_c11'] 	= 1,
			['card_cigcard_veh_c12'] 	= 1,
		}},
}

return Missions